### ISSUE TITLE
The solution for deepestChild() fails to get the deepest child if div has more then one direct child 

### ISSUE THREAD

**Issue by talgoldfus** [learn-co-curriculum/javascript-hide-and-seek#1]
Suggested solution for this would be : 

function deepestChild() {
  var answer
  var children = {}
  var counter = 0
  var list = document.querySelectorAll('#grand-node > div')
  for (var i = 0; i < list.length; i++) {
    var current_child = list[i]
    while (current_child.querySelector(':first-child') != null) {
      counter += 1
      current_child = current_child.querySelector(':first-child')
      deepestChild = current_child

```
}
if (children[i] === undefined || children[i] < counter) {
  children[i] = counter
  answer = deepestChild
}
counter = 0
```

  }
  return answer
}

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by pletcher** [comment]
Good catch, thanks!

**Comment by pletcher** [comment]
The solution that you've proposed works if there are siblings at the first child level, but not for branches below that. Implementing a proper [DFS](https://en.wikipedia.org/wiki/Depth-first_search) feels like it would be asking too much of students at this point, so I'm going to fix this by adding a caveat to the README that constrains the problem a bit.

**Comment by JaydR119** [comment]
thank you @pletcher this was driving me up the wall. node list kept returning empty
