### ISSUE TITLE
Feedback on 4th bullet / task

### ISSUE THREAD

**Issue by jkaneta** [learn-co-curriculum/javascript-hide-and-seek#11]
> Define a function deepestChild() that pulls out the most deeply nested child from div#grand-node
I found this to slightly ambiguous - I was not certain whether to return the last child (ie. \<div\>) or the element of that child. Perhaps reword as '...most deeply nested child element...' for clarification?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @jkaneta.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
