### ISSUE TITLE
open index.html command doesn't word in the ide's command line

### ISSUE THREAD

**Issue by luwo1701** [learn-co-curriculum/javascript-hide-and-seek#13]
For this lab it istructs you to call "open index.html" in terminal and "mocha.run()" in the developer console.
 One of the TA's pointed out i should instead call "httpserver". 

I then realized putting number returned after "Your server is running at" into my browser would show me the resulting webpage where i could open the developer console and then mocha.run(). 

I'm just thinking since the program suggests to use the IDE that there be a bit about that in the writeup to make it easier for other student. 

Cheers 🍻

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
