### ISSUE TITLE
Open command doesn't work with in browser IDE

### ISSUE THREAD

**Issue by hansenjl** [learn-co-curriculum/javascript-hide-and-seek#14]
With the In-browser IDE, the first instructions do not work:

"Call `open index.html` from your terminal, open your Chrome developer tools and call `mocha.run()` from your console to run the tests."

The `open` command gives you this error message: `bash: open: command not found` 

Instead, students should be asked to run `learn` and giving instructions on how to use `httpserver` so that they can view the index.html file in the browser. 

@DanielSeehausen

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @hansenjl.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
