### ISSUE TITLE
mocha.run() doesn't pass tests even though they pass when running learn

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/javascript-hide-and-seek#17]
A student found that when running learn, tests pass, but fail in the browser when running mocha.run() as the lesson instructs.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by nmalayev** [comment]
I came across the same issue that @d-d-d-dalia described. Turns out that the index-test.js file has some errors at lines 4, 11, 18, 33, and 40 - the toEqual() function is written as to.equal(). @NStephenson helped me figure out the issue.
