### ISSUE TITLE
Bad link in Git instructions for standalone editors

### ISSUE THREAD

**Issue by RylanBauermeister** [learn-co-curriculum/javascript-hide-and-seek#21]
Text reads: "[these instructions][instructions]"
Assuming that this is running on a basic markup engine, it should read: "[these instructions](instructions)" where instructions is a variable connected to a web URL.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
