### ISSUE TITLE
Suggestion for In-Browser Learn IDE users starting httpserver

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/javascript-hide-and-seek#23]
When I started **httpserver** on my In-Browser Learn IDE I found I could not use the command line to test my progress (e.g. _learn_ command).  So, I sent the program to the background using '&' or CTRL-Z and 'bg'.  I thought this might be useful for others.  However, I did log off a session without killing the background process and the next time I ran the server, it had to use a different IP/port.  Not sure the change was related, but if so, perhaps when a user session ends (or when they begin a new one) the server can be shut down and IP/port freed.

**Comment by drakeltheryuujin** [comment]
Our product team can help with this. I've submitted a request for the changes to be made in Learn.co documentation.

Raising issues on GitHub, like you've done here should happen when there are problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can to clarify our error, and we will try to find a fix.
