### ISSUE TITLE
How to restore // ♥ prompt to terminal after creating server with "httpserver"?

### ISSUE THREAD

**Issue by s-blais** [learn-co-curriculum/javascript-hide-and-seek#25]
Hello

 the section "Instructions for In-Browser Learn IDE Users" in this lesson seems incomplete (unless I'm missing something?)

It's simple enough to follow the instructions to get the server's IP address and then open that in another window... but then we are not shown how to escape the resulting "ready for changes" server mode and return to the familiar Learn terminal prompt " //♥ " in order to be able to use "learn test" and "learn submit" ... unless we're not supposed to? It's not explained... 

There must be a simple way to get the //♥ prompt back – if so, what is it? – and shouldn't that be part of the instructions?

I was able to get "httpserver &" to work, to start the server as a background process, only after a combination of finding [this article](https://help.learn.co/articles/492970-running-multiple-processes-in-the-ide-terminal) and some experimentation with exiting and re-entering the lesson. 

Side note - there's also some nonfunctioning links in the "Instructions for Using an Stand Alone Text-Editor" section

Thank you!

**Comment by drakeltheryuujin** [comment]
Our product team can help with this. I've submitted a request for the changes to be made in Learn.co documentation.

Raising issues on GitHub, like you've done here should happen when there are problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can to clarify our error, and we will try to find a fix.
