### ISSUE TITLE
Confusing Examples

### ISSUE THREAD

**Issue by Madeline-Stark** [learn-co-curriculum/javascript-hide-and-seek#26]
Nested target requires a space between the id and class name in order to pass, but none of the lesson examples have a space in front of the class name.

**Comment by drakeltheryuujin** [comment]
Hi @Madeline-Stark,

`#nested.target` and `#nested .target` represent 2 different relationships in element targeting.

The first would be an element that has both an id of `nested` and a class of `target`.
The second would be a parent element with the id of `nested` that has a child element with a class of `target`. 

We have updated the materials to try to make it more clear. Thanks for your contribution! 💙
