### ISSUE TITLE
there is a typo in the 67th line of the code missing a closed parentheses

### ISSUE THREAD

**Issue by imdavidy** [learn-co-curriculum/javascript-hide-and-seek#3]
There is a missing parentheses after the end of the first sentence of this paragraph.

In the above example, the first query says, "Starting from `document` (the object we've called `querySelector()` on), find a `ul` with a `className` of `ranked-list` (the `.` is for `className` #). Then find an `li` that is a child of that `ul`. Then find a `ul` that is a child (but not necessarily a direct descendant) of that `li`. Finally, find an `li` that is a child of that (second) `ul`."

**Comment by JessRudder** [comment]
Fixed!  Thanks.
