### ISSUE TITLE
deepestChild() passes line 18 test with incorrect code

### ISSUE THREAD

**Issue by jd2rogers2** [learn-co-curriculum/javascript-hide-and-seek#5]
track: bootcamp-prep
summary: test is expecting function to return value of inner most div but passes even whilst returning outermost div
files: test/index-test.js (line 18 expectation is the issue)
solution: i'm stumped sorry
mention: @aturkewi 

![screen shot 2017-01-06 at 4 06 51 pm](https://cloud.githubusercontent.com/assets/16400333/21733261/749bd7ee-d42b-11e6-8da3-c945b95e5d2f.png)

![screen shot 2017-01-06 at 4 21 27 pm](https://cloud.githubusercontent.com/assets/16400333/21733401/41da5244-d42c-11e6-9ada-052e8914636b.png)

**Comment by aturkewi** [comment]
Fixed with PR #4
