### ISSUE TITLE
Console.log not printing to the console

### ISSUE THREAD

**Issue by lucketta** [learn-co-curriculum/javascript-hide-and-seek#6]
Trying to figure out why console.log isn't printing to the screen for me.

console.log("TEST") is a simple example and I don't see anything on the console. Have asked learn experts twice about it, but they don't seem to have a fix for me. Is this a bug with the IDE?

**Comment by JessRudder** [comment]
Hi @lucketta thanks for reaching out.  This is specifically for issues on a given lab.  If you're still having issues with the IDE and a Learn Expert can't help, please reach out to technical support through support@learn.co.
