### ISSUE TITLE
Specs do not match readme

### ISSUE THREAD

**Issue by larissaschiavo** [learn-co-curriculum/javascript-hide-and-seek#9]
The specs are slightly out of order w/ the readme - a little confusing if working through in order- switch the order of spec #3 with spec #4 to match the readme

<img width="1104" alt="screen shot 2017-09-01 at 3 41 54 pm" src="https://user-images.githubusercontent.com/22383400/29990039-21853c82-8f2c-11e7-9d94-95ddcd489122.png">
<img width="659" alt="screen shot 2017-09-01 at 3 41 41 pm" src="https://user-images.githubusercontent.com/22383400/29990040-21866364-8f2c-11e7-8c68-7442488b9d5a.png">

**Comment by larissaschiavo** [comment]
(note, this is after finishing 2 of the specs - there are 4 total specs)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @larissaschiavo.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
